### ISSUE TITLE
How do we change the default Database name or username for Container in junit test in Junit5?

### ISSUE THREAD

**Issue by ShubhamShekhar1996** [testcontainers/testcontainers-java-spring-boot-quickstart#11]
How do we change the default Database name or username and container port for Container in junit test in Junit5?
By default it takes everything as test.
Junit5, Spring boot- 3.1.3

**Comment by kauanmocelin** [comment]
You can do it like this to change default values for database name, username and password:
```java
private static final PostgreSQLContainer<?> postgresContainer = new PostgreSQLContainer<>(DockerImageName.parse(
    "postgres:16-alpine"
))
    .withDatabaseName("")
    .withUsername("")
    .withPassword("");
``` 
Ports on host are generated randomly by design. You can get more information in the official documentation: [Exposing container ports to the host](https://java.testcontainers.org/features/networking/)

**Comment by kiview** [comment]
Closed, since it is not an issue, but a question and answered by @kauanmocelin, thanks 🙌
