### ISSUE TITLE
Configure scripts per test in Spring boot 3.1 test containers configuration

### ISSUE THREAD

**Issue by macg20** [testcontainers/testcontainers-java-spring-boot-quickstart#6]
I prepared data scripts per test in Spring Boot 3.1 and Postgres. How can i configure 
script with @BeforeAll annotation in new spring boot style? As described this chapter "Using Spring Boot 3.1.0 @ServiceConnection" for new spring boot test containers configuration. 

Old way:

```
var containerDelegate = new JdbcDatabaseDelegate(postgreSQLContainer, "");
var scripts = new PathMatchingResourcePatternResolver().getResources(directory);
var scriptDir = new PathMatchingResourcePatternResolver().getResource("db");
for (Resource script : scripts) {
    ScriptUtils.runInitScript(containerDelegate,
        Paths.get("db", scriptDir.getFile().toPath().relativize(script.getFile().toPath()).toString()).toString());
}
```

How is new way?

**Comment by sivaprasadreddy** [comment]
If you have separate SQL script for tests then you can use `@Sql("script_name.sql")` annotation on test method that will be executed by Spring.

**Comment by macg20** [comment]
Not working with spring-boot-starter flyway. Flyway applied migrations:
logback: 11:55:37.595 [Test worker] INFO  o.f.core.internal.command.DbMigrate - Successfully applied 10 migrations 
I created simple insert script, and next run with  @Sql("simple.sql") on the method/class. 
I get communicate from pg container : "relation not exists" . When run debug mode, tables are created. (Run without @Sql)

**Comment by sivaprasadreddy** [comment]
Can you create a issue reproducer so that I can take a look at it?

**Comment by macg20** [comment]
My bad. Resolved it. But i have another problem.  Open new issue.
